mlops 3
lewagon/taxi-fare pull request #11
Opened 2022-04-20 06:24 UTC by gmanchon

add tests

2022-04-20 10:50 UTC, krokrob requested changes
Good start @gmanchon ! I think the instructions, takeaways and assessment should be more visible in the READMEs. Continue the good work!

2022-04-20 10:50 UTC, krokrob commented on versioned/02/02_README_setup.md
> +- python code running on your machine has access to your GCP account
```suggestion
- Python code running on your machine has access to your GCP account
```

2022-04-20 10:50 UTC, krokrob commented on versioned/02/02_README_setup.md
> +Let's create a **bucket** that you will use to store files in the cloud if you do not already have one.
Is it a challenge? If so it has to be clearer, what is expected.

I see they should use `gsutil mb gs://BUCKET_NAME`

2022-04-20 10:50 UTC, krokrob commented on versioned/02/02_README_setup.md
> +Find the `gcloud` command allowing you to list your **GCP project id**.
This is a key takeaway of the challenge so it should appear as such.

E.g.

### ❓How do you list your GCP projects?

2022-04-20 10:50 UTC, krokrob commented on versioned/02/02_README_setup.md
> +Use it to fill the `PROJECT_ID` variable in the `Makefile`.
This is an assessment and must be visible

E.g.

### 📝 Fill the `PROJECT_ID` variable in the `Makefile`

2022-04-20 10:50 UTC, krokrob commented on versioned/02/02_README_setup.md
> +Use it to fill the `PROJECT_ID` variable in the `Makefile`.
Then run the test with `make dev_test`

2022-04-20 10:50 UTC, krokrob commented on versioned/02/02_README_setup.md
> +Find the `gsutil` command allowing you to retrieve the name of your **bucket**.
Key takeaway

2022-04-20 10:50 UTC, krokrob commented on versioned/02/02_README_setup.md
> +Use it to fill the `BUCKET_NAME` variable in the `Makefile`.
Assessment

2022-04-20 10:50 UTC, krokrob commented on versioned/02/02_README_setup.md
> +Use it to fill the `BUCKET_NAME` variable in the `Makefile`.
then run `make dev_test`

2022-04-20 15:40 UTC, krokrob requested changes
Nice! I have some more suggestion then I'm done, everything will be fine 🙈

2022-04-20 15:40 UTC, krokrob commented on versioned/02/02_README_setup.md
> +📝 **Run the first `4` tests** with `make dev_test` to verify that:
```bash
📝 **Run the first `4` tests** with `make dev_test` in your terminal to verify that:
```

2022-04-20 15:40 UTC, krokrob commented on versioned/02/02_README_setup.md
> +
Do you mean the first 4 tests should be green at this point? If so, let's precise it:
```suggestion

The first 4 tests should be ✅. If they are not, check the _hint_. 

```

And are we sure they will be displayed in the right order?

2022-04-20 15:40 UTC, krokrob commented on versioned/02/02_README_setup.md
> +Then run the test with `make dev_test`.
We could specify which tests should pass after that point

2022-04-20 15:40 UTC, krokrob commented on versioned/02/02_README_setup.md
> +The second CLI tool that you will use often allows to deal with files stored in the cloud.
```suggestion
The second CLI tool that you will use often allows you to deal with files stored in the cloud.
```

2022-04-20 15:40 UTC, krokrob commented on versioned/02/02_README_setup.md
> +📝 **Create a bucket in your GCP account**
```suggestion
💻 **Create a bucket in your GCP account**
```

2022-04-20 15:40 UTC, krokrob commented on versioned/02/02_README_setup.md
> +Then run the test with `make dev_test`.
All tests should pass! 👏

2022-04-20 15:40 UTC, krokrob commented on versioned/02/02_README_setup.md
> +Then run the test with `make dev_test`.
Specify which tests should pass or suggest that more tests should pass (8/12 for instance...)

2022-04-20 16:35 UTC, gmanchon commented on versioned/02/02_README_setup.md
> +
concerning the order that would be true only because I am not currently running the tests of the package itself...

@krokrob should we have them manually `TEST_ENV=development pytest -s tests/test_setup.py` for this one rather than use the make command ? (or should we create a dedicated make command for this one ?

2022-04-20 16:38 UTC, gmanchon commented on versioned/02/02_README_setup.md
> +
I'll create a dedicated command :)

2022-04-20 17:17 UTC, gmanchon commented
@krokrob thanks for your feedback ! 🙏 I renamed the tests to try to have shorter and clearer names, and added a docstring for the TAs, but the errors should be self explanatory. WDYT ?

2022-04-21 08:42 UTC, krokrob requested changes
I think we forgot to write the `.txt` file before running the tests...

2022-04-21 08:42 UTC, krokrob commented on versioned/02/02_README_setup.md
> +Then run the test with `make dev_test` (`test_setup_bucket_name` should be ✅).
```suggestion
Then run the tests with `make dev_test` (`test_setup_bucket_name` should be ✅).
```

2022-04-21 08:42 UTC, krokrob commented on model/Makefile
> +	TEST_ENV=development PYTHONDONTWRITEBYTECODE=1 pytest -v --color=yes
```
write_results && TEST_ENV=development PYTHONDONTWRITEBYTECODE=1 pytest -v --color=yes
```

2022-04-21 09:00 UTC, gmanchon commented on model/Makefile
> +	TEST_ENV=development PYTHONDONTWRITEBYTECODE=1 pytest -v --color=yes
I added the [instruction](https://github.com/lewagon/taxi-fare/pull/11/commits/5b42fdc1deb74f98e5196d3bca8e9dfc8bef66c8)

2022-04-21 09:00 UTC, gmanchon commented
@krokrob all good 😁

2022-04-27 08:01 UTC, krokrob approved these changes

2022-04-27 08:02 UTC, merged