cloud training
lewagon/taxi-fare pull request #15
Opened 2022-04-22 14:07 UTC by gmanchon

adds cloud training challenge with working tests

2022-04-28 15:07 UTC, krokrob requested changes
Nice challenge to discover CLI commands 👏 , I have a lot of questions and suggestions, that would be awesome!
Maybe we need a kind of `sandbox.py` close to the `main.py` to be able to perform some test script, for instance comparing training time with local vs Cloud Storage vs BQ data sourcing, WDYT?

2022-04-28 15:07 UTC, krokrob commented on versioned/02/03_README_cloud_data.md
> +Then run the test with `make dev_test` (`test_cloud_data_table_name` and `test_cloud_data_bq_chunks` should be ✅).
```suggestion
**🧪 Run the test with `make dev_test`**

👉 `test_cloud_data_table_name` and `test_cloud_data_bq_chunks` should be ✅
```

2022-04-28 15:07 UTC, krokrob commented on versioned/02/03_README_cloud_data.md
> +Then run the test with `make dev_test` (`test_cloud_data_table_name` and `test_cloud_data_bq_chunks` should be ✅).
⚠️ `test_cloud_data_table_name` does not exist

2022-04-28 15:07 UTC, krokrob commented on versioned/02/03_README_cloud_data.md
> +You have adapted your package to be able to source data incrementally in the cloud from either Cloud Storage or Big Query.
```suggestion
🏁 Congrats! You have adapted your package to be able to source data incrementally in the cloud from either Cloud Storage or Big Query.
```

2022-04-28 15:07 UTC, krokrob commented on versioned/02/03_README_cloud_data.md
> +Now we will see how to perform the training itself in the cloud!
I suggest to remove the teaser

2022-05-01 08:48 UTC, gmanchon commented on versioned/02/03_README_cloud_data.md
> +📝 **Fill the `BUCKET_NAME` variable in the `taxifare_model.ml_logic.params` module**
I like the idea of referring to the code in terms of packages and modules instead of directories and files. It sounds more pythonic and the syntax is shorter (and OS independant). The syntax is also closer to the `python -m package.module` call type which is better than calling files directly for the imports... WDTY ?

2022-05-01 08:51 UTC, gmanchon commented on versioned/02/03_README_cloud_data.md
> +Then run the test with `make dev_test` (`test_cloud_data_dataset_blob_uri` should be ✅).
it is hidden in `tests/unittests/test_data_cloud_data.py`

2022-05-05 17:22 UTC, gmanchon commented on versioned/02/03_README_cloud_data.md
> +Then run the test with `make dev_test` (`test_cloud_data_table_name` and `test_cloud_data_bq_chunks` should be ✅).
it is stored in `tests/unittests/test_data_cloud_data.py`

2022-05-05 17:24 UTC, gmanchon commented on versioned/02/03_README_cloud_data.md
> +📝 **Fill the `DATASET`, `TRAINING_TABLE` and `VALIDATION_TABLE` variables in the `taxifare_model.ml_logic.params` module**
@brunolajoie is ok with the module terminology if you agree

2022-05-05 18:07 UTC, gmanchon commented on versioned/02/03_README_cloud_data.md
> +  Then you would provide the full schema of the table as an argument to the command with `--schema "key:timestamp,fare_amount:float,..."`
True, this field makes no sense, but I want to encourage the students to use the find the `--autodetect` option that builds the schema for them, and this option detects a timestamp. I prefer to have all the students use the exact same schema for the table. I would rather they all have the same issues when loading the data into dataframes so that the TA are not confused. I will be more assertive about the data types to used. WDYT ?

2022-05-05 18:15 UTC, gmanchon commented on model/tests/test_cloud_data.py
> +        assert "640000" in training_content
_10000_ is the number of lines in the csv and _640000_ the space occupied by the data. I guess the difference came from the use of string vs timestamp. I added instructions to fix the data types requirements

2022-05-05 18:24 UTC, gmanchon commented on versioned/02/03_README_cloud_data.md
> +👉 see how Big Query can be slower to retrieve data depending on the chunk size that is used
Let's remove this comment 👍

2022-05-05 18:42 UTC, gmanchon commented on versioned/02/03_README_cloud_data.md
> +👉 See how the training is a little longer since the code is fetching data over the network for each chunk
I added instructions for the student to time the command : https://github.com/lewagon/taxi-fare/pull/15/commits/47f1057477c068b6a7d4746eaff39ffc6a164da0

2022-05-05 18:44 UTC, gmanchon commented
Thanks @krokrob, I opted for the easy solution by having the students time their trainings with data from Cloud Storage vs BQ using the `time` command

I will be coming back to this challenge to correct the tests since the functions used in order to name the ressources depending on the dataset have evolved in the new codebase

2022-05-05 18:44 UTC, merged