cloud training
lewagon/taxi-fare pull request #22
Opened 2022-04-24 13:03 UTC by gmanchon

challenge with tests

2022-04-29 16:10 UTC, krokrob requested changes
@gmanchon this is a partial review as I am stuck in the process of setting up the VM, let's discuss when I return

2022-04-29 16:10 UTC, krokrob commented on versioned/02/04_README_cloud_training.md
> +  sudo apt install -y zsh
```suggestion
  sudo apt install -y zsh git
```

2022-04-29 16:10 UTC, krokrob commented on versioned/02/04_README_cloud_training.md
> +  git clone https://github.com/pyenv/pyenv-virtualenv.git $(pyenv root)/plugins/pyenv-virtualenv
I got:
```
zsh: command not found: pyenv
```
 I think I need to restart the terminal... 😅

2022-05-06 13:28 UTC, gmanchon commented on versioned/02/04_README_cloud_training.md
> +Head towards the GCP console [Compute Engine](https://console.cloud.google.com/compute) page. The console will allow you to explore easilly the options available.
done 👍

2022-05-06 13:35 UTC, gmanchon commented on versioned/02/04_README_cloud_training.md
> +💻 **Create a VM instance and fill the `INSTANCE` variable in the `Makefile`**
I added instructions to have a look at the how to and read the hint. The default config is ok but you need to create a Ubuntu instance so that all the students use the same conf

2022-05-06 13:36 UTC, gmanchon commented on versioned/02/04_README_cloud_training.md
> +💻 **Create a VM instance and fill the `INSTANCE` variable in the `Makefile`**
The CLI also allows to create a ubuntu instance, I will add a test to check the instance OS

2022-05-06 19:52 UTC, gmanchon commented on versioned/02/04_README_cloud_training.md
> +  git clone https://github.com/pyenv/pyenv.git ~/.pyenv
git will be available out of the box for the students choosing an ubuntu image 👌

2022-05-06 19:53 UTC, gmanchon commented on versioned/02/04_README_cloud_training.md
> +  sudo apt install -y zsh
available out of the box in ubuntu

2022-05-06 20:05 UTC, gmanchon commented on versioned/02/04_README_cloud_training.md
> +  git clone https://github.com/pyenv/pyenv-virtualenv.git $(pyenv root)/plugins/pyenv-virtualenv
I think I did the setup 2 or 3 times and specifically paid attention to the required restarts. Maybe I forgot one but it seems to me that they are not required. Can you try the setup with an ubuntu image ?

2022-05-06 20:10 UTC, gmanchon commented on versioned/02/04_README_cloud_training.md
let's do that ! 💪

2022-05-06 20:11 UTC, merged