Mlops add model v0
lewagon/taxi-fare pull request #4
Opened 2022-04-06 15:31 UTC by brunolajoie

**MVP of taxifare_model package**

- Working code inside `model/taxifare_model` but ugly and in need of refacto.
- `main.py` contains training routes which can train on a limited number of rows
- `main_incremental.py` contains training routes which can train incrementally on an unlimited number of rows
- no challengify TAG yet

@gmanchon you don't need to review the code inside `model/taxifare_model` not any `model/notebooks`, but you can
- Check the other files diffs
- Try to `pip install -e .` from `model` folder?
- Then check that you can run `python taxifare_model/main.py` and `python taxifare_model/main_incremental.py`? Stop the execution of the second one, it takes 40min to run ATM :D 
- Merge if you good

2022-04-06 16:08 UTC, brunolajoie commented
Sorry no need to review notebook either, they are all WIP

2022-04-07 07:04 UTC, gmanchon commented
@brunolajoie looks great, I did not dig into the `.gitignore` files, vscode `settings.json` or `tests` too much. The package installs correctly and the imports work 👍

2022-04-07 07:04 UTC, gmanchon requested changes

2022-04-07 07:04 UTC, gmanchon commented on model/setup.py
> +with open('requirements.txt') as f:
should we commit to single or double quotes everywhere ? PEP8 does not make a recommandation (only to use double quotes for multiline strings)

personally I use double quotes but we can decide what we want...

```suggestion
with open("requirements.txt") as f:
```

2022-04-07 07:07 UTC, gmanchon commented
I trained from the `model` directory using `python -m taxifare_model.main` and `python -m taxifare_model.main_incremental`

2022-04-07 08:49 UTC, brunolajoie commented on model/tests/unittests/test_data.py
> +import pytest
Cool! Yes, will do later with 
![image](https://user-images.githubusercontent.com/22095643/162160000-46224988-e237-42cf-81f8-20387494e065.png)

2022-04-07 08:51 UTC, brunolajoie commented
ok, sure, i'll yapf the whole thing later anyway, this was just an ugly but working MVP

2022-04-07 10:01 UTC, merged

2022-04-07 12:54 UTC, gmanchon commented
pretty cool MVP and going to be awesome 🔥