add mlops lecture livecodes
lewagon/taxi-fare pull request #90
Opened 2022-07-29 08:30 UTC by gmanchon

2022-07-29 10:22 UTC, krokrob reviewed
1 question

2022-07-29 10:22 UTC, krokrob commented on .challengify_iterate.yml
> +    cloud_lecture:            02-Cloud-training/Lecture-livecode
does myriad handle challenge without numbers?

2022-07-29 10:22 UTC, krokrob commented on .challengify_iterate.yml
> +    lifecycle_lecture:        03-Automate-model-lifecycle/Lecture-livecode
same here

2022-07-29 12:24 UTC, gmanchon commented on .challengify_iterate.yml
> +    cloud_lecture:            02-Cloud-training/Lecture-livecode
omg, well played, I missed that ! 🙏

2022-07-29 12:40 UTC, gmanchon commented
@krokrob I renamed the challenges in this PR + https://github.com/lewagon/data-meta/pull/249 + https://github.com/lewagon/data-solutions/pull/1110

2022-08-01 08:50 UTC, krokrob commented on notebooks/Lecture-livecode-Automate-model-lifecycle.ipynb
> +{
<p>no more <code>model</code> directory </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/lewagon/taxi-fare/pull/90/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='1'/>

2022-08-01 08:50 UTC, krokrob commented on notebooks/Lecture-livecode-Automate-model-lifecycle.ipynb
> +{
<p>replace interace w/ interface</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/lewagon/taxi-fare/pull/90/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='16'/>

2022-08-01 08:50 UTC, krokrob commented on notebooks/Lecture-livecode-Automate-model-lifecycle.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #1.    from taxifare_model.interface.main import (preprocess, train, evaluate)
</pre><p>from taxifare.interface</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/lewagon/taxi-fare/pull/90/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='17'/>

2022-08-01 08:50 UTC, krokrob commented on notebooks/Lecture-livecode-Automate-model-lifecycle.ipynb
> +{
<p>same here</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/lewagon/taxi-fare/pull/90/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='19'/>

2022-08-01 08:50 UTC, krokrob commented on notebooks/Lecture-livecode-Automate-model-lifecycle.ipynb
> +{
<p>sane here 😂</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/lewagon/taxi-fare/pull/90/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='22'/>

2022-08-01 08:50 UTC, krokrob commented on notebooks/Lecture-livecode-Automate-model-lifecycle.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #1.    from taxifare_model.interface.main import (preprocess, train, evaluate)
</pre><p>same here</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/lewagon/taxi-fare/pull/90/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='23'/>

2022-08-01 08:50 UTC, krokrob commented on notebooks/Lecture-livecode-Cloud-Training.ipynb
> +{
<p>/model does not exist anymore</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/lewagon/taxi-fare/pull/90/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='1'/>

2022-08-01 08:50 UTC, krokrob commented on notebooks/Lecture-livecode-Cloud-Training.ipynb
> +{
<p>I can't see <code>model_target</code> directory neither </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/lewagon/taxi-fare/pull/90/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='7'/>

2022-08-01 08:50 UTC, krokrob commented on notebooks/Lecture-livecode-Cloud-Training.ipynb
> +{
<p>same here</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/lewagon/taxi-fare/pull/90/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='9'/>

2022-08-01 08:50 UTC, krokrob commented on notebooks/Lecture-livecode-Cloud-Training.ipynb
> +{
<p>same here</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/lewagon/taxi-fare/pull/90/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='19'/>

2022-08-01 08:50 UTC, krokrob commented
@gmanchon review done

2022-08-01 12:42 UTC, gmanchon commented on notebooks/Lecture-livecode-Automate-model-lifecycle.ipynb
> +{
<p>thx :pray:</p>

2022-08-01 12:43 UTC, gmanchon commented on notebooks/Lecture-livecode-Automate-model-lifecycle.ipynb
> +{
<p>😅</p>

2022-08-01 12:46 UTC, gmanchon commented on notebooks/Lecture-livecode-Automate-model-lifecycle.ipynb
> +{
<p>🙏</p>

2022-08-01 12:47 UTC, krokrob requested changes
@gmanchon thanks, I have a question and you have a conflict

2022-08-01 12:47 UTC, krokrob commented on notebooks/Lecture-livecode-Automate-model-lifecycle.ipynb
> +    "cd data-challenges/07-ML-Ops/03-Automate-model-lifecycle/01-Lecture-livecode\n",
Doesn't `cd <local_path_to('07-ML-Ops/03-Automate-model-lifecycle/01-Lecture-livecode')>` do the trick?

2022-08-01 12:47 UTC, krokrob commented on notebooks/Lecture-livecode-Cloud-Training.ipynb
> +    "cd data-challenges/07-ML-Ops/02-Cloud-training/01-Lecture-livecode\n",
same here

2022-08-01 12:50 UTC, merged

2022-08-01 12:50 UTC, gmanchon commented
@krokrob good to go, I had to locally merge mlops-reorg into the branch for the conflict to appear 🤔